#!/usr/bin/env bash
set -euo pipefail
DIGITS="${1:-10000000}"
TASK_DEPTH="${2:-5}"
LEAF_SIZE="${3:-128}"
TASK_MIN_SIZE="${4:-4096}"
MERGE_TASK_DEPTH_LIMIT="${5:-2}"
MERGE_TASK_MIN_SIZE="${6:-65536}"

export OMP_NUM_THREADS="${OMP_NUM_THREADS:-8}"
export OMP_PROC_BIND="${OMP_PROC_BIND:-close}"
export OMP_PLACES="${OMP_PLACES:-cores}"

echo "[env] OMP_NUM_THREADS=$OMP_NUM_THREADS OMP_PROC_BIND=$OMP_PROC_BIND OMP_PLACES=$OMP_PLACES"
./pi_bs_yc_inspired "$DIGITS" "$TASK_DEPTH" "$LEAF_SIZE" "$TASK_MIN_SIZE" "$MERGE_TASK_DEPTH_LIMIT" "$MERGE_TASK_MIN_SIZE"
